
export const catalogItem5 =  {
  id: 5,
  img: 'catalog5_jtxnmc',
  title: 'catalog.itemName',
  names:'names',
  price: 900,
  decs: 'catalog.itemDesc',
  subDesc: 'catalog.itemSubDesc',
  notAvailable:false,
  namesSub:null,
  path:'osmos_purification-system',
  detailsList:["detailsList[0]","detailsList[1]","detailsList[2]"],
  specs: {
    type: 'specs[0]',
    placement: 'specs[1]',
    capacity: 'specs[2]',
    voltage: 'specs[3]',
    power_summer_winter: 'specs[4]',
    dimensions: 'specs[5]',
    weight: 'specs[6]',
  },
  specsLabels:{
    type: 'specsLabels[0]',
    placement: 'specsLabels[1]',
    capacity: 'specsLabels[2]',
    voltage: 'specsLabels[3]',
    power_summer_winter: 'specsLabels[4]',
    dimensions: 'specsLabels[5]',
    weight: 'specsLabels[6]',
  },
  details: {
    door_material: 'details[0]',
    body_material: 'details[1]',
    wall_insulation: 'details[2]',
    internal_insulation: 'details[3]',
    water_dispense_door: 'details[4]',
    water_dispense_lighting: 'details[5]',
    water_dispense_faucet: 'details[6]',
  },
  detailsLabels: {
    door_material: 'detailsLabels[0]',
    body_material: 'detailsLabels[1]',
    wall_insulation: 'detailsLabels[2]',
    internal_insulation: 'detailsLabels[3]',
    water_dispense_door: 'detailsLabels[4]',
    water_dispense_lighting: 'detailsLabels[5]',
    water_dispense_faucet: 'detailsLabels[6]',
  },
  options: {
    remote_monitoring: 'options[0]',
    qr_codes: 'options[1]',
    customer_card: 'options[2]',
    fiscal_registrar: 'options[3]',
    bill_acceptor: 'options[4]',
    coin_acceptor: 'options[5]',
    offline_work: 'options[6]',
  },
  optionsLabels: {
    remote_monitoring: 'optionsLabels[0]',
    qr_codes: 'optionsLabels[1]',
    customer_card: 'optionsLabels[2]',
    fiscal_registrar: 'optionsLabels[3]',
    bill_acceptor: 'optionsLabels[4]',
    coin_acceptor: 'optionsLabels[5]',
    offline_work: 'optionsLabels[6]',
  },
  components: [
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
    { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true }
    
  ],

sliderMainBig:['OsmosSlider1.png','OsmosSlider2.png','OsmosSlider3.png','https://www.youtube.com/embed/qwoU3222Qis?si=1RB1KxR1RevoNarw'],
sliderMainSmall: [
  { src: 'OsmosSlider1.png', type: 'image' },
  { src: 'OsmosSlider2.png', type: 'image' },
  { src: 'OsmosSlider3.png', type: 'image' },
  { src: 'octicon:play-24', type: 'video' }

],
exampleGallery:null,

}
