export const catalogItem1 = {
    id: 1,
    img: 'catalog1_g2oi4w',
    title: 'catalog.itemName',
    price: 3100,
    decs: 'catalog.itemDesc',
    subDesc: 'catalog.itemSubDesc',
    path:'vending_machine-floor',
    notAvailable:false,
    names:'names',
    namesSub:null,
    specs: {
      type: 'specs[0]',
      placement: 'specs[1]',
      capacity: 'specs[2]',
      voltage: 'specs[3]',
      power_summer_winter: 'specs[4]',
      dimensions: 'specs[5]',
      weight: 'specs[6]',
    },
    specsLabels:{
      type: 'specsLabels[0]',
      placement: 'specsLabels[1]',
      capacity: 'specsLabels[2]',
      voltage: 'specsLabels[3]',
      power_summer_winter: 'specsLabels[4]',
      dimensions: 'specsLabels[5]',
      weight: 'specsLabels[6]',
    },
    details: {
      door_material: 'details[0]',
      body_material: 'details[1]',
      wall_insulation: 'details[2]',
      internal_insulation: 'details[3]',
      water_dispense_door: 'details[4]',
      water_dispense_lighting: 'details[5]',
      water_dispense_faucet: 'details[6]',
    },
    detailsLabels: {
      door_material: 'detailsLabels[0]',
      body_material: 'detailsLabels[1]',
      wall_insulation: 'detailsLabels[2]',
      internal_insulation: 'detailsLabels[3]',
      water_dispense_door: 'detailsLabels[4]',
      water_dispense_lighting: 'detailsLabels[5]',
      water_dispense_faucet: 'detailsLabels[6]',
    },
    options: {
      remote_monitoring: 'options[0]',
      qr_codes: 'options[1]',
      customer_card: 'options[2]',
      fiscal_registrar: 'options[3]',
      bill_acceptor: 'options[4]',
      coin_acceptor: 'options[5]',
      offline_work: 'options[6]',
    },
    optionsLabels: {
      remote_monitoring: 'optionsLabels[0]',
      qr_codes: 'optionsLabels[1]',
      customer_card: 'optionsLabels[2]',
      fiscal_registrar: 'optionsLabels[3]',
      bill_acceptor: 'optionsLabels[4]',
      coin_acceptor: 'optionsLabels[5]',
      offline_work: 'optionsLabels[6]',
    },
    detailsList:["detailsList[0]","detailsList[1]","detailsList[2]"],
    components: [
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 2 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 2 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
    ],
  
  sliderMainBig:['catalogSliderMainBig.png','catalogSliderMainBig2.png','catalogSliderMainBig3.png','https://www.youtube.com/embed/Iu7IeLYReOE?modestbranding=0&showinfo=1&controls=1&loop=1&playlist=Iu7IeLYReOE','https://www.youtube.com/embed/-IemGZwDp2s','https://www.youtube.com/embed/SRRVL-kpCHw'],
  sliderMainSmall: [
    { src: 'catalogSliderMainSmall1.png', type: 'image' },
    { src: 'catalogSliderMainSmall2.png', type: 'image' },
    { src: 'catalogSliderMainSmall3.png', type: 'image' },
    { src: 'octicon:play-24', type: 'video' },
    { src: 'octicon:play-24', type: 'video' },
    { src: 'octicon:play-24', type: 'video' }
  ],
  exampleGallery:['new1_idhcft','new2_luor9g','new3_ksag6c','gallery1.jpg','gallery2.jpg','gallery3.jpg','gallery4.jpg','gallery5.jpg','gallery6.jpg','gallery7.jpg','gallery8.jpg','gallery9.jpg',],
  };