export const catalogItem3 =  {
    id: 3,
    img: 'catalog3_tenmbi',
    title: 'catalog.itemName',
    price: 1450,
    decs: 'catalog.itemDesc',
    subDesc: 'catalog.itemSubDesc',
    path:'vending_machine-wall-mounted',
    notAvailable:false,
    names:'names',
    namesSub:null,
    specs: {
      type: 'specs[0]',
      placement: 'specs[1]',
      capacity: 'specs[2]',
      voltage: 'specs[3]',
      power_summer_winter: 'specs[4]',
      dimensions: 'specs[5]',
      weight: 'specs[6]',
    },
    specsLabels:{
      type: 'specsLabels[0]',
      placement: 'specsLabels[1]',
      capacity: 'specsLabels[2]',
      voltage: 'specsLabels[3]',
      power_summer_winter: 'specsLabels[4]',
      dimensions: 'specsLabels[5]',
      weight: 'specsLabels[6]',
    },
    details: {
      door_material: 'details[0]',
      body_material: 'details[1]',
      wall_insulation: 'details[2]',
      internal_insulation: 'details[3]',
      water_dispense_door: 'details[4]',
      water_dispense_lighting: 'details[5]',
      water_dispense_faucet: 'details[6]',
    },
    detailsLabels: {
      door_material: 'detailsLabels[0]',
      body_material: 'detailsLabels[1]',
      wall_insulation: 'detailsLabels[2]',
      internal_insulation: 'detailsLabels[3]',
      water_dispense_door: 'detailsLabels[4]',
      water_dispense_lighting: 'detailsLabels[5]',
      water_dispense_faucet: 'detailsLabels[6]',
    },
    options: {
      remote_monitoring: 'options[0]',
      qr_codes: 'options[1]',
      customer_card: 'options[2]',
      fiscal_registrar: 'options[3]',
      bill_acceptor: 'options[4]',
      coin_acceptor: 'options[5]',
      offline_work: 'options[6]',
    },
    optionsLabels: {
      remote_monitoring: 'optionsLabels[0]',
      qr_codes: 'optionsLabels[1]',
      customer_card: 'optionsLabels[2]',
      fiscal_registrar: 'optionsLabels[3]',
      bill_acceptor: 'optionsLabels[4]',
      coin_acceptor: 'optionsLabels[5]',
      offline_work: 'optionsLabels[6]',
    },
    detailsList:["detailsList[0]","detailsList[1]","detailsList[2]"],
    components: [
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 2,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 2 ,hasIcon: true},
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true }, 
      { name: 'table.name', params: 'table.params', quantity: 1,hasIcon: true },
      { name: 'table.name', params: 'table.params', quantity: '-' },
      { name: 'table.name', params: 'table.params', quantity: '-' },
      { name: 'table.name', params: 'table.params', quantity: '-' },
     
    ],


sliderMainBig:['wall1.png','wall2.png','https://www.youtube.com/embed/6BpjktEM4eU?si=1zDcCeUU2v_u8yEc'],
sliderMainSmall: [
  { src: 'wall1.png', type: 'image' },
  { src: 'wall2.png', type: 'image' },
  { src: 'octicon:play-24', type: 'video' },
 
 
],
exampleGallery:['wellGallery1.jpg','wellGallery2.jpg','wellGallery3.jpg'],


  }